### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by cyouh95** [tadmint/prj-rev-bwfs-dasmoto#4]
(Exceeds Expectations)

Great job on this project! Not only did you perfectly recreate the webpage, your code is properly spaced and indented, making it very easy to read and follow.

As a further challenge, consider building on top of this page and explore the different ways to display and style all the elements- you are ready for it! When you do, keep in mind some of the good coding practices (including using multiple selectors #1) to help keep your code succinct and clear.

**Comment by tadmint** [comment]
Thank you!
